[package]
name = "audio-resample"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.21"
cpal = "0.15.3"
env_logger = "0.11.5"
fixedvec = "0.2.4"
hound = "3.5.1"
log = "0.4.22"
ringbuf = "0.4.7"
rubato = "0.16.1"
