// Configuration for the output device. This is what every audio stream will be resampled to.
pub const OUTPUT_DEVICE_SAMPLE_RATE: usize = 48000;
pub const OUTPUT_DEVICE_CHANNELS: usize = 2;
pub const OUTPUT_DEVICE_BUFFER_SIZE_MS: usize = 10;
pub const OUTPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES: usize =
    (OUTPUT_DEVICE_SAMPLE_RATE / 1000) * OUTPUT_DEVICE_BUFFER_SIZE_MS;

pub const OUTPUT_DEVICE_BUFFER_SIZE_IN_BYTES: usize =
    OUTPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES * OUTPUT_DEVICE_CHANNELS * size_of::<f32>() as usize;

pub const OUTPUT_DEVICE_BUFFER_SIZE_IN_PCM_SAMPLES: usize =
    OUTPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES * OUTPUT_DEVICE_CHANNELS;

pub const INPUT_DEVICE_SAMPLE_RATE: usize = 48000;
pub const INPUT_DEVICE_CHANNELS: usize = 1;
pub const INPUT_DEVICE_BUFFER_SIZE_MS: usize = 10;
pub const INPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES: usize =
    (INPUT_DEVICE_SAMPLE_RATE / 1000) * INPUT_DEVICE_BUFFER_SIZE_MS;

pub const INPUT_DEVICE_BUFFER_SIZE_IN_BYTES: usize =
    INPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES * INPUT_DEVICE_CHANNELS * size_of::<f32>() as usize;

pub const INPUT_DEVICE_BUFFER_SIZE_IN_PCM_SAMPLES: usize =
    INPUT_DEVICE_BUFFER_SIZE_IN_SAMPLES * INPUT_DEVICE_CHANNELS;
